cc_library(
    name = "World",
    srcs = [
        "Company.h",
        "Company.cpp",
        "Investor.cpp",
        "Investor.h",
        "Person.h",
        "Person.cpp",
        "Stock.h",
        "Stock.cpp",
        "World.h",
        "World.cpp",
        "NameGenerator.h"
    ],
    deps = [
        "@json//:json",
        "@boost//:asio",
        "@boost//:beast",
    ],
    visibility = ["//:__pkg__"]
)