cc_library(
    name = "Map",
    srcs = [
        "Map.h",
        "Map.cpp",
        "Coordinate.cpp",
        "Coordinate.h",
        "Resource.cpp",
        "Resource.h",
    ],
    visibility = ["//:__subpackages__"]
)