cc_library(
    name = "Humanity",
    srcs = [
        "Person.h",
        "Person.cpp",
        "Building.h",
        "Building.cpp",
    ],
    deps = [
        "//WorldSim/Map:Map",
        "@json//:json",
        "@boost//:asio",
        "@boost//:beast",
    ],
        visibility = ["//:__subpackages__"]
)