cc_library(
    name = "api",
    srcs = [
        "BuyDto.h",
        "CompanyDto.h",
        "CompanyInvestorDto.h",
        "InvestorDto.h",
        "RegisterInvestorDto.h",
    ],
    deps = [
        "//Deserializable:Deserializable",
    ],
    visibility = ["//visibility:public"]
)