load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")


# Trading bot dependencies
load("@bazel_tools//tools/build_defs/repo:git.bzl", "git_repository")

http_archive(
    name = "rules_python",
    sha256 = "8c8fe44ef0a9afc256d1e75ad5f448bb59b81aba149b8958f02f7b3a98f5d9b4",
    strip_prefix = "rules_python-0.13.0",
    url = "https://github.com/bazelbuild/rules_python/archive/refs/tags/0.13.0.tar.gz",
)


load("@rules_python//python:pip.bzl", "pip_parse")

pip_parse(
   name = "my_deps",
   requirements = "//:requirements_lock.txt",
)

load("@my_deps//:requirements.bzl", "install_deps")
install_deps()


http_archive(
    name = "market_sim",
    strip_prefix = "MarketSim-0.0.2",
    url = "https://github.com/LaurieHarding-Russell/MarketSim/archive/refs/tags/v0.0.2.tar.gz",
    sha256 = "5d85c38f599ec2a89ae7c580d5beddfacd3d3a01c0360e30afdfc1cd0ce90d65"
)


RULES_OPEN_API_COMMIT = "f48152c4a204b1b9c59d726579ce416aa5d08732"
RULES_OPEN_API_SHA256 = "1d6bdad4608e99708cc7818ffdca9d5ae4c74857d002f19330ae8a028868f258"

http_archive(
    name = "io_bazel_rules_openapi",
    strip_prefix = "rules_openapi-%s" % RULES_OPEN_API_COMMIT,
    url = "https://github.com/meetup/rules_openapi/archive/%s.tar.gz" % RULES_OPEN_API_COMMIT,
    sha256 = RULES_OPEN_API_SHA256
)

load("@io_bazel_rules_openapi//openapi:openapi.bzl", "openapi_repositories")
openapi_repositories(
    codegen_cli_version = "5.0.0",
    codegen_cli_sha256 = "839fade01e54ce1eecf012b8c33adb1413cff0cf2e76e23bc8d7673f09626f8e",
    codegen_cli_provider = "openapi"
)



# Java deps
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

RULES_JVM_EXTERNAL_TAG = "4.2"
RULES_JVM_EXTERNAL_SHA = "cd1a77b7b02e8e008439ca76fd34f5b07aecb8c752961f9640dea15e9e5ba1ca"

http_archive(
    name = "rules_jvm_external",
    strip_prefix = "rules_jvm_external-%s" % RULES_JVM_EXTERNAL_TAG,
    sha256 = RULES_JVM_EXTERNAL_SHA,
    url = "https://github.com/bazelbuild/rules_jvm_external/archive/%s.zip" % RULES_JVM_EXTERNAL_TAG,
)

load("@rules_jvm_external//:repositories.bzl", "rules_jvm_external_deps")

rules_jvm_external_deps()

load("@rules_jvm_external//:setup.bzl", "rules_jvm_external_setup")

rules_jvm_external_setup()

load("@rules_jvm_external//:defs.bzl", "maven_install")

maven_install(
    artifacts = [
        "io.swagger:swagger-models:1.5.18",
        "io.swagger:swagger-annotations:1.5.18",
        "com.squareup.okhttp3:okhttp:3.14.7",
        "com.squareup.okio:okio:3.2.0",
        "com.squareup.okio:okio-jvm:3.2.0",
        "com.squareup.okhttp3:logging-interceptor:3.14.7",
        "com.google.code.gson:gson:2.8.6",
        "io.gsonfire:gson-fire:1.8.4",
        "org.apache.commons:commons-lang3:3.10",
        "org.threeten:threetenbp:1.4.3",
        "com.google.code.findbugs:jsr305:3.0.2",
        "javax.servlet:servlet-api:2.5",
        "javax.validation:validation-api:1.1.0.Final",
        "javax.xml.bind:jaxb-api:2.3.0",
        "javax.ws.rs:jsr311-api:1.1.1",
        "javax.annotation:javax.annotation-api:1.3.2",
    ],
    repositories = [
        "https://maven.google.com",
        "https://repo1.maven.org/maven2",
    ],
)